
INPUT:
  SIZE_TRAIN: [256, 128] # vehicle: [256,256]
  SIZE_TEST: [256, 128] # vehicle: [256,256]
  DO_AUTOAUG: False


META:
  BOTTLENECK:
    DO_IT: False #
    REDUCTION_DIM: 1024 
    NORM: True 
  DATA:
    NAMES: "" #
    NUM_VIEW: 4 
  REGULARIZER:
    LR_FACTOR: 10.0
    DO_IT: False # No reg
  MODEL:
    LR_FACTOR: 1.0 
    SPLIT_LAYER: ('',) # No Meta
  SOLVER:
    INIT: 
      NUM_EPOCH: 0 
      INNER_LOOP: 1 
      OUTER_LOOP: 40 
    MTRAIN: 
      IMS_PER_BATCH: 128 
      NUM_INSTANCE: 1 
      INNER_LOOP: 1 
      INNER_LOOP_TYPE: 'same'
      NUM_DOMAIN: 3 
    MTEST: 
      IMS_PER_BATCH: 128 
      NUM_INSTANCE: 1 
      ONLY_ONE_DOMAIN: False 
    FINAL: 
      NUM_EPOCH: 0 
      STEPS: [30,60]
      INITIALIZE_CONV_STATE_META: 'pretrained' 
      INITIALIZE_CONV_STATE_ORI: 'pretrained' 
      INITIALIZE_CONV: True 
      INITIALIZE_FC: True
      DETAIL_MODE: False
      WEIGHT_LOADER: None 
      WEIGHT_FOLDER: None 
      SAVE_META_PARAM: True 
    WRITE_PERIOD: 20
    NO_TRAIN_ORIGINAL: False 
    SYNC: True 
  LOSS:
    META_REG_WEIGHT: 0.001
    ORI_REG_WEIGHT: 0.01 
    INIT_NAME: ("CrossEntropyLoss",)
    MTRAIN_NAME: ("CrossEntropyLoss", "Reg_bottleneck","Reg_classifier",) 
    MTEST_NAME: ("CrossEntropyLoss", )


MODEL:
  META_ARCHITECTURE: "Metalearning" 
  BACKBONE:
    WITH_IBN: True 
    PRETRAIN: True 
    PRETRAIN_PATH: 'pretrained/resnet50_ibn_a.pth' 
    NORM: "BN" 
  HEADS:
    NAME: "MetalearningHead" 
    NUM_CLASSES: 575
    POOL_LAYER: "avgpool"
    BT_NORM: "BN"
    NORM: "BN" 
  LOSSES:
    TRI:
      HARD_MINING: True
      MARGIN: 0.3 # vehicle: 0.0
    NAME: ("CrossEntropyLoss", "TripletLoss",)

DATASETS:
#  NAMES: ("VeRi_keypoint",)
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  AMP: True 
  OPT: "Adam" # SGD
  BASE_LR: 0.00035 # 0.01
  ETA_MIN_LR: 7.7e-5

  MAX_ITER: 120 # vehicle: 100
  STEPS: [40, 90] # vehicle: [40, 70]

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 20
  IMS_PER_BATCH: 64
  WEIGHT_DECAY: 0.0005 
  WEIGHT_DECAY_BIAS: 0.0005 
  WRITE_PERIOD: 50 
  MOMENTUM: 0.9 

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

