#_BASE_: "../Base-bagtricks.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  DO_AUTOAUG: False


META:  ############################################
  BOTTLENECK:
    DO_IT: True
    REDUCTION_DIM: 1024 
    NORM: True 
  DATA:
    NAMES: "VeRi_keypoint_each_4" # 'VeRi_keypoint_each_2', ('VeRi_keypoint_each_4'), 'VeRi_keypoint_each_8'
    NUM_VIEW: 4 # 2, (4), 8
  REGULARIZER:
    LR_FACTOR: 10.0 # [reg] 1.0, (10.0), 100.0
  MODEL:
    LR_FACTOR: 1.0 # [meta] 0.1, (1.0), 10.0
    SPLIT_LAYER: ("bottleneck","classifier",) # "bottleneck","classifier","bnneck","pooling",
  SOLVER:
    INIT: 
      NUM_EPOCH: 0 # [first init (k x 6 minute)] (0), 5, 10
      INNER_LOOP: 1 # [second init] (1), 5
      OUTER_LOOP: 40 # [meta-optmization] 1, (5)
    MTRAIN: 
      IMS_PER_BATCH: 128 # 32, (64), 128
      NUM_INSTANCE: 1 # 2, (4), 8
      INNER_LOOP: 1 # memory, not working
      INNER_LOOP_TYPE: 'same' # memory, not working
      NUM_DOMAIN: 3 # (1), 2, 3
    MTEST: 
      IMS_PER_BATCH: 128 # 32, (64), 128
      NUM_INSTANCE: 1 # 2, (4), 8
      ONLY_ONE_DOMAIN: False # [False is more fast] True, (False)
    FINAL: 
      NUM_EPOCH: 90 # [k x 60 minute]
      STEPS: [30,60]
      INITIALIZE_CONV_STATE_META: 'pretrained' # ('pretrained'), 'scratch'
      INITIALIZE_CONV_STATE_ORI: 'pretrained' # ('pretrained'), 'scratch'
      INITIALIZE_CONV: True # (True), False
      INITIALIZE_FC: True # (True), False
      DETAIL_MODE: False
      WEIGHT_LOADER: None # [''.pth] or None
      WEIGHT_FOLDER: None # [./log/~~] or None
      SAVE_META_PARAM: True 
    WRITE_PERIOD: 5
    NO_TRAIN_ORIGINAL: False # True is no train!!
    SYNC: True 
  LOSS:
    META_REG_WEIGHT: 0.001 # 0.01, 0.001, 0.0001 (after saving)
    ORI_REG_WEIGHT: 0.01 # 0.01, 0.001, 0.0001 (after saving)
    INIT_NAME: ("CrossEntropyLoss",) # ("CrossEntropyLoss", "TripletLoss",)
    MTRAIN_NAME: ("CrossEntropyLoss", "Reg_bottleneck","Reg_classifier",) # ("CrossEntropyLoss", "TripletLoss", "Reg_bottleneck", "Reg_classifier",)
    MTEST_NAME: ("CrossEntropyLoss", ) # ("CrossEntropyLoss", "TripletLoss",)


MODEL:
  META_ARCHITECTURE: "Metalearning" 
  BACKBONE:
    WITH_IBN: True # True, (False) "pretrained/resnet50_ibn_a.pth"
    PRETRAIN: True 
    PRETRAIN_PATH: 'pretrained/resnet50_ibn_a.pth' 
    NORM: "BN" # BN / BIN_gate
  HEADS:
    NAME: "MetalearningHead" 
    NUM_CLASSES: 575
    POOL_LAYER: "avgpool"
    BT_NORM: "BN"
    NORM: "BN" # BN / BIN_gate
  LOSSES:
    TRI:
      HARD_MINING: True
      MARGIN: 0.0
    NAME: ("CrossEntropyLoss", "TripletLoss", "Reg_bottleneck","Reg_classifier",) # ("CrossEntropyLoss", "TripletLoss", "Reg_bottleneck", "Reg_classifier",)

DATASETS:
  NAMES: ("VeRi_keypoint",)
  TESTS: ("VeRi",)

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  AMP: True # AMP need recent version more than pytorch 1.6
  OPT: "SGD"
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5

  MAX_ITER: 100
  STEPS: [40, 70]

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 20
  IMS_PER_BATCH: 64
  WEIGHT_DECAY: 0.0005 # 0, (0.0005) (after saving)
  WEIGHT_DECAY_BIAS: 0.0005 # 0, (0.0005) (after saving)
  WRITE_PERIOD: 50 
  MOMENTUM: 0.9 # 0, (0.9)

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

